.PHONY: all

all : etc/libdb.txt dist/build.jar

etc/libdb.txt : etc/libdb.raw scripts/updatelibdb
	updatelibdb

dist/build.jar : Makefile src/makebuilder/BuildFileLoader.java src/makebuilder/SourceFileHandler.java src/makebuilder/SrcFile.java src/makebuilder/handler/Qt4Handler.java src/makebuilder/handler/ScriptHandler.java src/makebuilder/handler/NvccHandler.java src/makebuilder/handler/MakeXMLLoader.java src/makebuilder/handler/JavaHandler.java src/makebuilder/handler/CppMerger.java src/makebuilder/handler/CppHandler.java src/makebuilder/util/AddOrderSet.java src/makebuilder/util/CCOptions.java src/makebuilder/util/ToStringComparator.java src/makebuilder/util/ExtensionFilenameFilter.java src/makebuilder/util/GCC.java src/makebuilder/util/CodeBlock.java src/makebuilder/util/Files.java src/makebuilder/util/Util.java src/makebuilder/MakeFileBuilder.java src/makebuilder/Options.java src/makebuilder/SourceScanner.java src/makebuilder/DotFile.java src/makebuilder/StartScript.java src/makebuilder/BuildEntity.java src/makebuilder/Library.java src/makebuilder/SrcDir.java src/makebuilder/ext/CakeHandler.java src/makebuilder/ext/finroc/FinrocRepositoryTargetCreator.java src/makebuilder/ext/finroc/LdPreloadScriptHandler.java src/makebuilder/ext/finroc/FinrocPlugin.java src/makebuilder/ext/finroc/TestProgram.java src/makebuilder/ext/finroc/RRLib.java src/makebuilder/ext/finroc/FinrocBuilder.java src/makebuilder/ext/finroc/FinrocLibrary.java src/makebuilder/ext/finroc/FinrocProgram.java src/makebuilder/ext/finroc/FinrocBuildEntity.java src/makebuilder/ext/mca/DescriptionBuilderHandler.java src/makebuilder/ext/mca/MCABuildEntity.java src/makebuilder/ext/mca/SConscriptConverter.java src/makebuilder/ext/mca/MCA2RepositoryTargetCreator.java src/makebuilder/ext/mca/MCABuilder.java src/makebuilder/ext/mca/MCAProgram.java src/makebuilder/ext/mca/EtcDirCopier.java src/makebuilder/ext/mca/HFileCopier.java src/makebuilder/ext/mca/MCALibrary.java src/makebuilder/ext/mca/virtualrepo/VirtualRepositoryBuilder.java src/makebuilder/ext/mca/LibInfoGenerator.java src/makebuilder/ext/mca/MCAPlugin.java src/makebuilder/ext/mca/DependencyHandler.java src/makebuilder/ext/mca/MCASystemLibLoader.java src/makebuilder/ext/mca/SConscriptParser.java src/makebuilder/libdb/LibDB.java src/makebuilder/RepositoryTargetCreator.java src/makebuilder/Blacklist.java src/makebuilder/Makefile.java src/makebuilder/Program.java src/makebuilder/handler/EnumStringsBuilderHandler.java
	ant
	rm -f ../.makeBuilderCache


