#!/bin/bash
cd $MCAHOME
cd make_builder
make
cd ..
rm Makefile
java -Xmx256M -jar make_builder/dist/build.jar makebuilder.ext.mca.MCABuilder --build=$MCATARGET --combine --usesysteminstall
makeCall "$@"


