#!/usr/bin/perl -w

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
#----------------------------------------------------------------------
# \file    print_default_include_paths
#
# \author  Max Reichardt
#
# \date    2016-07-14
#
# Prints the default include paths for system libraries used by the system's compiler 
# (one path per line)
#
#----------------------------------------------------------------------

use strict;

my $CALL = "echo | cpp -Wp,-v 2>&1";
my @lines = `$CALL`;

foreach (@lines) {
  my $line = $_;
  $line =~ s/^\s+|\s+$//g;     # remove both leading and trailing whitespace
  while ($line =~ /^(\/\S*)/g)
  {
    print "$1\n";
  }
}

